# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-5.6.2
apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.kubernetes.cri-o.SandboxID/friendlygoldwasser: c734f661b146fe9ef720f44583024dfdb150ffe7a971e5fc16b5155c9971d566
  creationTimestamp: "2025-11-17T11:56:17Z"
  labels:
    app: demo-pod
  name: demo-pod
spec:
  containers:
  - args:
    - nginx
    - -g
    - daemon off;
    env:  
    image: localhost/scriptcamp/nginx:latest
    name: friendlygoldwasser
    ports:
    - containerPort: 80
      hostPort: 8080
    tty: true
